spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8081
ml.service.url=${https://ai-resume-analyzer-umra.onrender.com}