spring.application.name=backend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8081
ml.service.url=https://ai-resume-analyzer-umra.onrender.com
cors.allowed.origins=http://localhost:5173,http://localhost:5174,https://ai-resume-analyzer-nathsoham71.vercel.app,https://*.vercel.app